### ISSUE TITLE
The CMD version didn't go off of my default profile

### ISSUE THREAD

**Issue by themaneiac** [Sibusten/derpibooru-downloader#10]
I had it scheduled to run at midnight every night but it seems it didn't download based on my current profile :/
It downloaded 104 GB in C:\Windows\System32\Downloads before I found out it was still running. 
It downloaded just the images without the json files like the built in default profile.
Did I do something wrong?
If it used my custom profile it would have only downloaded yesterdays images since I already have all of Derpibooru downloaded.

**Comment by Sibusten** [comment]
I should write a section on how to do downloads with it in the readme, sorry about that.

To tell it to use a profile, you have to add the argument `--profile ProfileName`, where ProfileName is the name of the profile, exactly as it is spelled in the gui version. If you have an api key saved and want to use it, you also have to send `--use-saved-api-key`.

You also have to be careful with what the task scheduler sets as the "current directory". It may default to `C:\Windows\System32`, which means that if the program is told to save images in a relative directory such as `Downloads/`, it will start from whatever the current directory is (system32 in that case).
This can be fixed either by setting an absolute path in the file and json save formats, or by setting the working directory to the correct folder in your task scheduler. In Windows Task Scheduler, this is called "Start in".

**Comment by Sibusten** [comment]
Hopefully that helped to solve your issue. I've added some information to the readme about the cmd version.
