### ISSUE TITLE
Foreign Language Loading

### ISSUE THREAD

**Issue by Astrocities** [Sibusten/derpibooru-downloader#12]
There seems to be a problem when it comes to loading preset written in a different language, e.g. artist's name is written in Korean or in Japanese kanji. The image can be downloaded just fine into the specified artist's folder. But upon loading the preset, the file options are empty.

I am using v1.3.2.

Example tag: artist:부시벅

**Comment by Sibusten** [comment]
Thank you for the report.
v1.3.2 is out of date and may have issues. Please try updating to the newest version [v1.4.0](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.0) to see if the problem still exists.

**Comment by Astrocities** [comment]
Alright thanks. That fixed the problem.
