### ISSUE TITLE
Program downloading unrendered images

### ISSUE THREAD

**Issue by Sibusten** [Sibusten/derpibooru-downloader#14]
I do have a quick question.. Does this program detect not-yet-rendered files that just got uploaded? I have a thing that downloads all the images as they come out and a lot of files turn out like this instead of what the image is supposed to be: 
![sample](https://user-images.githubusercontent.com/6430050/47997528-05722500-e0b1-11e8-9d92-d8869e528c45.jpg)

Thank you!

_Originally posted by @themaneiac in https://github.com/Sibusten/derpibooru-downloader/issues/13#issuecomment-435853501_

**Comment by Sibusten** [comment]
@themaneiac
I've added a check to hopefully catch this. Try out the new release and let me know if it fixes the issue.
[v1.4.1](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.1)

**Comment by themaneiac** [comment]
This program hasn't been downloading any not yet rendered images. The other way I was downloading from Derpibooru downloaded a not yet rendered image every 1 out of 60 images on average. The most recent not yet rendered image I have is from when I was using that method. :)

**Comment by Sibusten** [comment]
Okay, cool. Seems like that fix worked
