### ISSUE TITLE
App crash 0xc000007b

### ISSUE THREAD

**Issue by Basinator89** [Sibusten/derpibooru-downloader#16]
The tool looks nice, but unfortunately crashes on starting (Win 7, ZIP).
 0xc000007b

Any software required otherwise?

**Comment by Sibusten** [comment]
Hello,
Do you happen to be running a 32 bit version of Windows 7? The app was compiled for 64 bit systems and won't run on 32 bit Windows.
I can look into compiling a 32 bit version if needed

**Comment by Basinator89** [comment]
64.
Does it depend on VS? I think that's broken on my system somehow.

**Comment by Sibusten** [comment]
Yes, it depends on Visual C++ 2015 Redistributable. If yours is broken, you can try reinstalling it from here: [Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685)

There also seemed to be an issue with the SSL dll files included in the release. I've swapped them out for a different version which appears to be working now. Try downloading [the new release](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.1) and see if that helps

**Comment by Basinator89** [comment]
I remember having issues with Teamspeak x64, x86 worked. Is it a trouble for you to compile x86 for me?

**Comment by Basinator89** [comment]
Thanks, x86 works for me for whatever reason, maybe I managed to break my x64 VS only, lol.

Downloads/{id}.{ext}
This is the default naming?

**Comment by Sibusten** [comment]
Cool, glad it's working.

Yes, that's the default file naming. There's a list of tags that can be used in the README and when hovering over the text field in the program.
