### ISSUE TITLE
[feature request] add 0 in front of if {month} and {day} only have 1 number 

### ISSUE THREAD

**Issue by ucok66** [Sibusten/derpibooru-downloader#19]
It may seem simple, but this might be a problem if you are arranging massive amounts of time-based images.

**Comment by Sibusten** [comment]
Strange, this should have been how the dates were handled. Thanks for the report, it is fixed in [v1.4.3](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.3)

**Comment by ucok66** [comment]
thanks for bug fix
