### ISSUE TITLE
Error with filters.

### ISSUE THREAD

**Issue by erintesden** [Sibusten/derpibooru-downloader#23]
Filters are working bad.

I tried to download this artist content, he have around 400 pics, but after being processed by my filter, only 320 were left in the webpage. 

But when i try to add, the api filter in the app, it only downloaded 53 pics and it stopped. The same if instead of the api i just type the tags i wanna hide in the search queary.
Theres a lot of included pics that arent being downloaded.

And if i use my user api, it just start to download EVERYTHING, even the pics i dont want. Its weird considering i have my filter on.

**Comment by Sibusten** [comment]
Hello,

Please double-check that the API Key you used is the correct API Key for your account.
Also make sure that the program says "Key given" above the API Key text input.

If those are correct, please give the search query you are trying to use on the site.

**Comment by erintesden** [comment]
Thanks for the fast answer.
Im not really sure what it was, maybe tha API was wrong like you put it, cuz after a lot of tries adding and removing it, it finally started to use the API filter of my account correctly.
So yeah, the thing resolved itself

**Comment by erintesden** [comment]
Thanks a lot for your work with this app, it was a lot usefull to me :)

**Comment by Sibusten** [comment]
You're welcome, I'm glad the issue was resolved
