### ISSUE TITLE
Question: does this download the max image size?

### ISSUE THREAD

**Issue by ProfHariSeldon** [Sibusten/derpibooru-downloader#26]
I want to download all pictures from one artist.

If I do that manually, then I can for example go to:
https://derpibooru.org/2052038
Then click Download to get the largest image size.
Repeat for other images

Does this program extract the largest image size too?  If so that would be a great help.

**Comment by Sibusten** [comment]
Yes, this program downloads the full size image. If you want to download images from that artist, for example, you would search for `artist:ravensunart`. Be sure to set the filter to `Everything` to get all images.
