### ISSUE TITLE
Downloader not working.

### ISSUE THREAD

**Issue by CommanderEwok** [Sibusten/derpibooru-downloader#29]
When I first used the downloader it worked perfectly. But after turning my machine off it now won't work except for when there's no tags selected. Then it starts downloading everything. I don't know what's wrong. I put the tags in the box, hit the button, there's a brief flash of a progress bar. And then nothing. I'm unsure as to what's wrong or how to fix it. Any help with this? I've tried both versions of the downloader and have tried deleting and re-downloading them a few times each now.

**Comment by CommanderEwok** [comment]
Sorry, I was trying to use the http box, not the tag itself. Really stupid of me.

**Comment by Sibusten** [comment]
No worries, glad you got it working!
