### ISSUE TITLE
Derpibooru API Changes

### ISSUE THREAD

**Issue by LunarNightShade** [Sibusten/derpibooru-downloader#30]
Derpibooru has migrated away from Rails and released their new server back-end, Philomena, that includes breaking API changes.

https://derpibooru.org/forums/meta/topics/philomena-open-beta-breaking-api-changes

> API changes
> 
> In the interest of preserving API compatibility, we will attempt to rewrite requests to our exisitng Rails JSON API for as long as is reasonably feasible after the migration (~ several months). We hope most applications will be able to migrate over to the new API format before we remove the Rails app completely.
> 
> As before, you can use the filter_id parameter to override your current filter, and the key parameter to authenticate yourself to the API. Here are the new API routes:
> 
> [[example]](https://philomena.derpibooru.org/api/v1/json/images/2125268) GET /api/v1/json/images/:image_id
> [[example]](https://philomena.derpibooru.org/api/v1/json/search?q=philomena&sf=updated_at) GET /api/v1/json/search
> [[example]](https://philomena.derpibooru.org/api/v1/json/oembed?url=https://derpibooru.org/2125268) GET /api/v1/json/oembed
> 
> There is also a POST route which takes a query parameter named URL. However, it depends on the scraper; do not expect it to work reliably until the scraper is fixed.
> 
> POST /api/v1/json/search/reverse
>

**Comment by Twi-Hard** [comment]
This was updated 2 hours ago https://derpibooru.org/pages/api

**Comment by liamwhite** [comment]
[Further updated](https://derpibooru.org/pages/api)

Note that if all you use is search, the changes are extremely minor, and should easily be adaptable to the new API.

**Comment by DonaldTsang** [comment]
Checking if this is fixed or not.

**Comment by Sibusten** [comment]
Everything should be using the new API now
