### ISSUE TITLE
Network Error - 302 - Bad Request

### ISSUE THREAD

**Issue by oblivion2k** [Sibusten/derpibooru-downloader#35]
Network Error - 302 - Error transferring https://www.derpibooru.org/search.json?q=test&page=1&perpage=50&sf=created_at&sd=desc&key=[omitted] - server replied: Bad Request

Error occurs with all queries.
Site is up and loads without issues.
API key is provided to the downloader.

**Comment by Sibusten** [comment]
Derpibooru may have removed their old API, as they had planned to do. Derpibooru Downloader v2.0.0 and up use the new API. Try using the newest release and see if that fixes it.

https://github.com/Sibusten/derpibooru-downloader/releases/tag/v2.0.0

**Comment by oblivion2k** [comment]
v2.0,0 fixed it, I didn't realize there was an update to the API or the downloader, my mistake.

I shouldn't troubleshoot without sleep :)
