### ISSUE TITLE
Cloudflare Captcha

### ISSUE THREAD

**Issue by huskyhi** [Sibusten/derpibooru-downloader#36]
It appears that Derpibooru has started to have Cloudflare Captcha screens while trying to download.
Is there a way to add a way to deal with the captcha?

**Comment by Sibusten** [comment]
Derpibooru is currently dealing with a DDoS attack. Hopefully this will clear and the Captchas will be removed. I will wait until more is known about the issue before trying anything.

**Comment by Sibusten** [comment]
I have not noticed persistent Captcha issues with the program. If the issues are still occurring, you may reopen this issue
