### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by HootHoot1** [Sibusten/derpibooru-downloader#38]
Hello!

In recent days an error started to occur whenever I want to use the downloader.

> Network Error - 302 - Error transferring https://derpibooru.org/search.json?q=batpony&page=1&perpage=50&sf=score&sd=desc&filter_id=100073 - server replied: Bad Request

What I found is that when I remove the '.json' part of the link, it opens in browser without any issues.
I suspect that derpi might have changed a thing on their side, but I'm not sure. I'm also not sure if I'm the only one experiencing this issue.

**Comment by Sibusten** [comment]
Yes, Derpibooru has recently updated to using a new API, and removed the old one. Please update to the newest version of the downloader, which uses the new API
