### ISSUE TITLE
Downloading a list of artists

### ISSUE THREAD

**Issue by TwiDash34** [Sibusten/derpibooru-downloader#39]
Здравствуйте. У меня есть список любимых художников, их около четырехсот. Раньше я загружал их другим загрузчиком, каждого в свою папку. Но так как он больше не поддерживается, решил попробовать ваш загрузчик. Как мне автоматизировть весь этот процесс? Неужели мне придется каждого отдельного художника через пресет вручную загружать?

**Comment by Sibusten** [comment]
> Hello. I have a list of favorite artists, there are about four hundred. I used to download them with another downloader, each in its own folder. But since it is no longer supported, I decided to try your downloader. How do I automate this whole process? Do I have to manually download each individual artist through a preset?

<hr>

Привет. Я использую Google Translate для общения. Вы можете сделать пресет для каждого художника, но это займет много времени и будет трудным. Если вы можете использовать версию командной строки, вы можете автоматизировать ее с помощью скрипта. Вы можете запустить такую команду для каждого имени исполнителя: `.\DerpibooruDownloaderCmd.exe -q "artist:<artist_name>" --filter 56027 --image-path "Downloads/<artist_name>/{id}.{ext}"` Замените `<artist_name>` каждым именем в вашем скрипте. Этот фильтр устанавливает фильтр "Everything".

Кроме того, я мог бы добавить способ получить имя исполнителя для имен файлов. Это позволило бы создать папку для каждого художника, используя только одну предустановку, но это не будет работать правильно, если на изображении более одного тега исполнителя.

> Hello. I am using Google Translate to talk. You could make a preset for each artist, but this will take a long time and be difficult. If you can use the command line version, you can automate it using a script. You can run a command like this for each artist name: `.\DerpibooruDownloaderCmd.exe -q "artist:<artist_name>" --filter 56027 --image-path "Downloads/<artist_name>/{id}.{ext}"`. Replace `<artist_name>` with each name in your script. That filter sets the "Everything" filter.
> 
>Alternatively, I could add a way to get the artist name for file names. This would allow making a folder for each artist using only one preset, but this will not work correctly if there is more than one artist tag on the image.

**Comment by TwiDash34** [comment]
> Привет. Я использую Переводчик Google для общения. Это может занять много времени и будет трудным. Вы можете автоматизировать ее с помощью скрипты. Вы можете запустить такую команду для каждого имени исполнителя : `.\DerpibooruDownloaderCmd.exe -q "artist:<artist_name>" --filter 56027 --image-path "Downloads/<artist_name>/{id}.{ext}"`Замените `<artist_name>`каждым Именем в вашем скрипте. Этот фильтр имеет фильтр "Все".
> 
> Кроме того, я могу добавить имя исполнителя для имен файлов. Это будет работать не только правильно, но и на одном исполнителе.


Этот скрипт немного упрощает задачу, но все же не решает проблему. Если это в ваших силах то сделайте пожалуйста возможность загрузки определенных художников из списка. Например в текстовом файле у меня будут перечислены художники в формате "artist:name", а программа просто будет брать их из списка и загружать каждого в свою папку. Некоторые файлы конечно будут дублироваться, из-за того что у одного изображения бывает несколько художников, но это ничего страшного :)

Так же очень сильно не хватает функции проверки ранее загруженных файлов. Например я загрузил определенную галерею, удалил не понравившиеся файлы. Но после запуска программы они загружаются снова. Хотелось бы что бы программа это понимала и загружала только новые файлы.

**Comment by Sibusten** [comment]
> This script simplifies the task a little, but still does not solve the problem. If this is within your power, please make it possible to download certain artists from the list. For example, in a text file, I will list artists in the format "artist: name", and the program will simply take them from the list and load each into its own folder. Some files will of course be duplicated, due to the fact that a single image has several artists, but that's okay :)
> 
> Also, the function of checking previously downloaded files is very lacking. For example, I downloaded a specific gallery, deleted files I didn’t like. But after starting the program, they load again. I would like the program to understand this and upload only new files.

<hr>

Это возможно с использованием версии командной строки, и вместо этого было бы намного проще автоматизировать это с помощью сценария. Я приложил скрипт, который делает это. Поместите его в тот же каталог, что и программа. Поместите имена художников в `artists.txt`. Не ставьте префикс `artist:`.

> This is possible using the command line version, and it would be much easier to automate this with a script instead. I have attached a script which does this. Put it in the same directory as the program. Put artist names in `artists.txt`. Do not put the prefix `artist:`.

[download-artists.zip](https://github.com/Sibusten/derpibooru-downloader/files/4596421/download-artists.zip)

Программа использует систему Derpibooru для фильтрации. Если есть фотографии, которые вам не нравятся, добавьте свой ключ API и используйте фильтр, который их скрывает, или спрячьте их вручную на сайте. Установите ключ API в программе `Gui`, затем используйте его в версии командной строки с `--use-saved-api-key`. Сценарий делает это.

> The program uses Derpibooru's system for filtering. If there are photos you do not like, add your API key and use a filter that hides them, or hide them manually on the site. Set the API key in the `Gui` program, then use it in the command line version with `--use-saved-api-key`. The script does this.
