### ISSUE TITLE
404 Error Handling

### ISSUE THREAD

**Issue by Astrocities** [Sibusten/derpibooru-downloader#4]
I noticed a pattern where the downloader will not progress past certain image ids, which also have a 404 Not Found on the download link to the image on the site. So the problem I have with searching through search tag query is that I will be stuck (e.g. 24/620 images, Elapsed 04:20:16) for an indefinite amount of time because the downloader can't download the image it is on.

**Comment by Sibusten** [comment]
I can look into finding a solution to this.

Do you have the id of the image causing this problem?

**Comment by Astrocities** [comment]
Ex. 906140 and 868596 to name a few.

**Comment by Sibusten** [comment]
Thanks, I'll look into it and see what I can do

**Comment by Sibusten** [comment]
Okay, I added error handling for missing images, they should now be skipped over and the downloader will continue running.

Please try this new version and let me know if it fixes the problem:

[Derpibooru Downloader v1.3.2](//github.com/Sibusten/derpibooru-downloader/releases/tag/v1.3.2)

**Comment by Astrocities** [comment]
Works much better now. Thanks.

**Comment by Sibusten** [comment]
You're welcome
