### ISSUE TITLE
Question about other Philomena boorus

### ISSUE THREAD

**Issue by nexusofconcordia** [Sibusten/derpibooru-downloader#43]
Hello! Will other Philomena boorus be supported in the future as well, or will this project stay Derpibooru exclusive?

**Comment by Sibusten** [comment]
It could be done if there is enough interest in it. The program is a bit frustrating to modify (5+ year old code). I've been working on a new browser and downloader for Philomena sites

**Comment by basisbit** [comment]
would be nice to to be able to specify a philomena server url as well as a philomena flavor (derpibooru/furbooru/booru) either in a config file or the UI. Also, thank you so much for continuing development of this software!!

**Comment by Sibusten** [comment]
I would likely do it as a text entry for the domain url, as that should be enough. Unsure whether it should be a global setting, or tied to the queries so it can be saved.

What do you mean by "flavor"?

**Comment by basisbit** [comment]
By flavor I meant the different not 100% same forks of philomena, which might have slightly different API?

**Comment by Sibusten** [comment]
Forks should not change existing API, or at least be compatible. This program will not need any special logic if that is the case, and I will not be adding support for sites which break the API.

**Comment by nexusofconcordia** [comment]
That's fair - and adding it as a text entry sounds like a good way to do it. Out of curiosity - 5 years old code? Is this based on the old command line tool that got abandoned then got several forks that update it?

**Comment by Sibusten** [comment]
Nope, I didn't know about any other downloaders when I first made this. It was originally just a scraping tool that got the newest images off Derpi, then I expanded it.

**Comment by Sibusten** [comment]
New release is up with this implemented: [v2.1.0](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v2.1.0)
