### ISSUE TITLE
I can't find out how to apply my derpibooru filters to the downloader

### ISSUE THREAD

**Issue by EliasAnimalCrossing** [Sibusten/derpibooru-downloader#49]
I keep trying to work out I'm suppose to do but I can't figure it out. How am I suppose to apply my derpibooru account filters to the derpibooru downloader? My account is on the .org version of derpibooru for the record.

**Comment by Sibusten** [comment]
To use private filters, you will need to set your API key. It can be found at https://derpibooru.org/registration/edit.
Paste your key into the API Key box and click Enter. Set your filter to "User Default" and it will use the filter you currently have on your account.

**Comment by Sibusten** [comment]
Sorry, typo in the link. It's corrected
