### ISSUE TITLE
Add feature to save to settings file instead of registry

### ISSUE THREAD

**Issue by EpicLPer** [Sibusten/derpibooru-downloader#5]
Since this is a fully portable program it'd make more sense to save the settings into a local file instead of the registry. If it's due to security concerns you could save the API key into registry but everything else into a normal file so it'd still stay portable without any security concerns.

**Comment by Sibusten** [comment]
That's a good idea. The reason it was saving to the registry was because I used the default options for the Settings class in the qt library. I am currently rewriting it to use an .ini file in the working directory instead, and to transfer settings from the old registry entry if they exist.

**Comment by Sibusten** [comment]
Okay, just posted a new release. Settings should now be saved to a local .ini file.

[Derpibooru Downloader v1.3.3](//github.com/Sibusten/derpibooru-downloader/releases/tag/v1.3.3)
