### ISSUE TITLE
Downloader function for Python/JS

### ISSUE THREAD

**Issue by BradKML** [Sibusten/derpibooru-downloader#54]
This is a C# based scraper that can only be called from the terminal. If one wants to use this to categorize images ala Python ML, what would be the best course of action?

**Comment by Sibusten** [comment]
This program is an executable and can only be called from the command line. If you want, you could try using the library [philomena-client](https://github.com/Sibusten/philomena-client) from Python, which includes most of the downloading functionality.

Some links I found in a search (not recommendations, I haven't tried anything like this):
https://stackoverflow.com/questions/7367976/calling-a-c-sharp-library-from-python
https://github.com/pythonnet/pythonnet
