### ISSUE TITLE
Download Directory

### ISSUE THREAD

**Issue by lylatveteran** [Sibusten/derpibooru-downloader#8]
Is there a way to change the location where the images are downloaded?

**Comment by Sibusten** [comment]
Yes, this can be done using the `Save Images As` path under `File Options`. You can use both relative and absolute paths. Below are two examples:

### Relative
`Downloads/{id}.{ext}`
Saves to a folder called `Downloads` in the current directory

### Absolute
`C://Derpibooru/{id}.{ext}`
Saves to the folder `C://Derpibooru/`
