### ISSUE TITLE
Way to schedule downloads?

### ISSUE THREAD

**Issue by themaneiac** [Sibusten/derpibooru-downloader#9]
I was wondering if you can add a way to schedule downloads? For example, allowing the program to be controlled with CMD?

**Comment by Sibusten** [comment]
I had thought about having a way to run downloads from the command line in the past, but there were some complications with Qt. I can look into it again and see what I can come up with, since this would be useful.

**Comment by themaneiac** [comment]
Thank You :)

**Comment by Sibusten** [comment]
I've just finished writing the command line version, download can be found here: [v1.4.0](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.0)
